google_analytics: UA-74277603-1

timezone: America/Los_Angeles
markdown: kramdown

kramdown:
  input: GFM

sass:
  sass_dir: _sass
  style: compressed

gems:
  - jekyll-sitemap

exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
